name: run
on:
  push:
    branches:
      - main
      - test
  schedule:
    - cron: "0,15,30,45 * * * *"
  workflow_dispatch: null

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: fast finish
      run: |
        set -x
        # avoid wasting CI time if there is nothing to do
        broken_count="$(ls broken/*.txt | grep -v broken/example.txt | wc -l)"
        not_broken_count="$(ls not_broken/*.txt | grep -v not_broken/example.txt | wc -l)"
        token_reset_count="$(ls token_reset/*.txt | grep -v token_reset/example.txt | wc -l)"
        archive_count="$(ls archive/*.txt | grep -v archive/example.txt | wc -l)"
        unarchive_count="$(ls unarchive/*.txt | grep -v unarchive/example.txt | wc -l)"
        grant_access_count="$(ls grant_access/*.txt | grep -v grant_access/example.txt | wc -l)"
        revoke_access_count="$(ls revoke_access/*.txt | grep -v revoke_access/example.txt | wc -l)"
        if [[ "${broken_count}" == "0" && "${not_broken_count}" == "0"
              && "${token_reset_count}" == "0" 
              && "${archive_count}" == "0" && "${unarchive_count}" == "0"
              && "${grant_access_count}" == "0" && "${revoke_access_count}" == "0"
        ]]; then
          echo "nothing to do, setting ci skip!"
          echo "CI_SKIP=true" >> $GITHUB_ENV
        fi

    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: cf
        environment-file: environment.yml
        auto-activate-base: true
        miniforge-version: latest
        miniforge-variant: Mambaforge
        use-mamba: true

    - name: Generate token
      id: generate_token
      uses: conda-forge/github-app-token@e3ab451d57e120b956292a1fa1d21fe4ba171c36
      with:
        app_id: ${{ secrets.CF_CURATOR_APP_ID }}
        private_key: ${{ secrets.CF_CURATOR_PRIVATE_KEY }}

    - name: Grant/Revoke access to resources
      shell: bash -el {0}
      run: |
        git config --global user.email "79913779+conda-forge-curator[bot]@users.noreply.github.com"
        git config --global user.name "conda-forge-curator[bot]"
        python access_control.py
      env:
        CIRUN_API_KEY: ${{ secrets.CIRUN_API_KEY }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        CIRUN_INSTALLATION_ID: ${{ secrets.CIRUN_INSTALLATION_ID }}

    - name: pull changes
      shell: bash -el {0}
      run: |
          git pull

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
